os: osx
osx_image: xcode9.4
language: generic

matrix:
  include:
    - python: 2.7
      env: TRAVIS_PYTHON_VERSION=2.7
    - python: 3.6
      env: TRAVIS_PYTHON_VERSION=3.6

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
    # Create environment
    - conda create -y --quiet -c conda-forge -n compas_fab compas scipy python=$TRAVIS_PYTHON_VERSION
    - conda activate compas_fab
    - pip install --no-cache-dir -r requirements-dev.txt

script:
- python -c "import compas_fab"
- python -c "import compas_fab.backends"
- python -c "from compas_fab.backends.vrep.remote_api import vrep"
- python -c "import compas_fab.robots"
- python -c "import compas_fab.utilities"
- pytest
- invoke docs
