# Base language is Python, but that does not work on macOs & Windows builds
language: python

matrix:
  include:
    - name: "Python 2.7: Windows"
      os: windows
      language: shell
      before_install:
        - choco install python2 vcredist2008
        - choco install --ignore-dependencies vcpython27
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
        - TRAVIS_PYTHON_VERSION=2.7
    - name: "Python 3.8: Windows"
      os: windows
      language: shell
      before_install:
        - choco install python3
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TRAVIS_PYTHON_VERSION=3.8
    - name: "Python 3.7: Xenial Linux"
      python: 3.7
      dist: xenial
      env: TRAVIS_PYTHON_VERSION=3.7
      services: docker
    - name: "Python 3.7: macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7

install:
  - pip install cython --install-option="--no-cython-compile"
  - pip install --no-cache-dir -r requirements-dev.txt

script:
  - python -c "import compas_fab"
  - python -c "import compas_fab.backends"
  - python -c "from compas_fab.backends.vrep.remote_api import vrep"
  - python -c "import compas_fab.robots"
  - python -c "import compas_fab.utilities"
  - pytest
  - invoke docs
