os: osx
osx_image: xcode9.4

language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install --no-cache-dir -r requirements-dev.txt

script:
- python -c "import compas_fab"
- python -c "import compas_fab.backends"
- python -c "from compas_fab.backends.vrep.remote_api import vrep"
- python -c "import compas_fab.robots"
- python -c "import compas_fab.utilities"
- pytest
- invoke docs
